export const materiaPorTurmas = {
            "INF-211": [
                "Artes I",
                "Biologia I",
                "Educação Física I",
                "Filosofia I",
                "Geografia I",
                "História I",
                "Língua Portuguesa e Literatura Brasileira I",
                "Matemática I",
                "Organização de Computadores",
                "Quimica Geral I",
                "Segurança, Meio Ambiente e Saúde",
                "Sociologia I",
            ],
            "INF-221": [
                "Artes II",
                "Biologia II",
                "Educação Física II",
                "Filosofia II",
                "Física I",
                "Geografia II",
                "História II",
                "Língua Portuguesa e Literatura Brasileira II",
                "Lógica Computacional",
                "Manutenção de Computadores",
                "Quimica Geral II",
                "Matemática II",
                "Sociologia II",
            ],
            "INF-231": [
                "Banco de Dados",
                "Biologia III",
                "Educação Física III",
                "Filosofia III",
                "Física II",
                "Geografia III",
                "Historia III",
                "Ingles Instrumental I",
                "Língua Portuguesa e Literatura Brasileira III",
                "Matematica III",
                "Programação I",
                "Quimica Organica",
                "Sociologia III",
            ],
            "INF-241": [
                "Biologia IV",
                "Desenvolvimento WEB I",
                "Educação física IV",
                "Filosofia IV",
                "Física III",
                "Fisico-Quimica I",
                "Geografia IV",
                "Historia IV",
                "Ingles Instrumental II",
                "Língua Portuguesa e Literatura Brasileira IV",
                "Matematica IV",
                "Programação II",
                "Redes de Computadores",
                "Sociologia IV",
            ],
            "INF-251": [
                "Biologia V",
                "Desenvolvimento WEB II",
                "Educação física V",
                "Filosofia V",
                "Física IV",
                "Fisico-Quimica II",
                "Geografia V",
                "Historia V",
                "Ingles Instrumental III",
                "Sistema Operacionais",
                "Projeto Computacional I",
                "Matematica V",
                "Língua Portuguesa e Literatura Brasileira V",
            ],
            "INF-261": [
                "Biologia VI",
                "Educação Física VI",
                "Física V",
                "História VI",
                "Ingles Instrumental IV",
                "Língua Portuguesa e Literatura Brasileira VI",
                "Matematica VI",
                "Midias, Tecnologias, ambiente e sociedade",
                "Projeto Computaional II",
                "Tecnologias Computacionais",
            ],
            "INF-OPT": [
                "Língua Espanhola I",
                "Língua Espanhola II",
                "Língua Espanhola III",
            ],
            "MAM-111": [
                "Artes I",
                "Biologia I",
                "Educação Física I",
                "Ética e Educação Ambiental",
                "Filosofia I",
                "Geografia I",
                "História I",
                "Legislação Ambiental I",
                "Língua Portuguesa e Literatura Brasileira I",
                "Matemática I",
                "Química Geral I",
                "Segurança, Meio Ambiente e Saúde",
                "Sociologia I"
            ],
            "MAM-121": [
                "Artes II",
                "Biologia II",
                "Educação Física II",
                "Filosofia II",
                "Física I",
                "Geografia Física",
                "Geografia II",
                "História II",
                "Legislação Ambiental II",
                "Língua Portuguesa e Literatura Brasileira II",
                "Matemática II",
                "Química Geral II",
                "Sociedade e Natureza I",
                "Sociologia II",
                "Técnicas Físico-Químicas de Separação"
            ],
            "MAM-131": [
                "Biologia III",
                "Educação Física III",
                "Filosofia III",
                "Física II",
                "História III",
                "Informática Aplicada",
                "Inglês Instrumental I",
                "Introdução aos Sistemas de Informação Geográfica",
                "Língua Portuguesa e Literatura Brasileira III",
                "Matemática III",
                "Princípios de Conservação da Natureza",
                "Química Orgânica",
                "Sociedade e Natureza II",
                "Sociologia III"
            ],
            "MAM-141": [
                "Biologia IV",
                "Climatologia",
                "Educação Física IV",
                "Filosofia IV",
                "Física III",
                "Físico-Química I",
                "Gerenciamento de Resíduos Sólidos",
                "História IV",
                "Identificação e Avaliação de Impactos Ambientais",
                "Inglês Instrumental II",
                "Língua Portuguesa e Literatura Brasileira IV",
                "Matemática IV",
                "Recursos Hídricos",
                "Sociologia IV"
            ],
            "MAM-151": [
                "Biologia V",
                "Ecologia e Ecossistemas Costeiros",
                "Educação Física V",
                "Elaboração de Projetos",
                "Filosofia V",
                "Física IV",
                "Físico-Química II",
                "História V",
                "Inglês Instrumental III",
                "Língua Portuguesa e Literatura Brasileira V",
                "Matemática V",
                "Movimentos Sociais e Meio Ambiente I",
                "Química Analítica I",
                "Sistemas de Gestão Ambiental e Sustentabilidade I"
            ],
            "MAM-161": [
                "Biologia VI",
                "Educação Física VI",
                "Filosofia VI",
                "Física V",
                "Geografia III",
                "História VI",
                "Inglês Instrumental IV",
                "Língua Portuguesa e Literatura Brasileira VI",
                "Matemática VI",
                "Movimentos Sociais e Meio Ambiente II",
                "Química Analítica II",
                "Sistemas de Gestão Ambiental e Sustentabilidade II"
            ],
            "MAM-OPT": [
                "Espanhol I",
                "Espanhol II",
                "Espanhol III"
            ],
            "TGA-311": [
                "Fontes de Energia e Eficiência Energética",
                "Geomorfologia e Hidrografia",
                "Inglês Instrumental",
                "Introdução á Gestão Ambiental" ,
                "Metodologia Cientifica",
                "Português Instrumental ",
                "Química Geral e Ambiental" ,
            ],
            "TGA-321": [
                "Direito Ambiental Aplicado",
                "Ecologia Geral",
                "Economia Ambiental e Solidária",
                "Educação Ambiental",
                "Estatística Aplicada",
                "Gestão de Recursos Hídricos e Saneamento",
                "Saúde e Segurança Ambiental"
            ],
            "TGA-331": [
                "Cartografia e Geoprocessamento",
                "Ecologia Politica",
                "Ecologia de Ecossistemas Costeiros",
                "Introdução a Gestão Pública",
                "Mudanças Climáticas e Adaptação",
                "Produção e Consumo Responsáveis",
                // "Optativa 1"
            ],
            "TGA-341": [
                "Direitos Humanos e Justiça Ambiental",
                "Elaboração de Projetos Acadêmicos e Ambientais",
                "Planejamento Urbano e Cidades Sustentáveis",
                "Princípios de Conservavação da Natureza",
                "Química Analítica",
                "Tratamento de Agua, Enfluentes Sanitários e Industriais",
                // "Optativa 2"
            ],
            "TGA-351": [
                "Gerenciamento de Resíduos Sólidos",
                "Gerenciamento de Resíduos Ambiental",
                "Gestão Ambiental e Auditoria",
                "Tecnologias Aplicadas",
                "Tópicos Especiais em Gestão Ambiental",
                "Atividades de Pesquisa e Extensão",
                // "Optativa 3"
            ],
            "TGA-OPT": [
                "Historia Agroambiental Comparada",
                "Populações Tradicionais e Territórios",
                "Agroecologia",
                "Globalização e Multiculturalismo",
                "Governança Socioambiental",
                "Seminários de Pesquisa e Extensão",
                "Libras"
            ],
            "TRC-311": [
                "Redes de Computadores I",
                "Organização de Computadores",
                "Metodologia Cientifica",
                "Inglês Instrumental I",
                "Matemática para Computação I",
                "Português Instrumental I"
            ],
            "TRC-321": [
                "Redes de Computadores II",
                "Introdução a Sistemas Operacionais",
                "Pesquisa, Tecnologia e Sociedade",
                "Algoritmos",
                "Inglês Instrumental II",
                "Matemática para Computação II",
                "Português Instrumental II"
            ],
            "TRC-331": [
                "Redes de Computadores III",
                "Sistemas Operacionais I",
                "Filosofia da Técnica",
                "Linguagem de Programação",
                "Sistemas para Internet"
            ],
            "TRC-341": [
                "Redes de Computadores IV",
                "Sistemas Operacionais II",
                "Segurança em Redes de Computadores",
                "Banco de Dados",
                "Princípios de Segurança da Informação"
            ],
            "TRC-351": [
                "Administração de Redes e Servidores",
                "Sistemas Operacionais III",
                "Projeto Integrador I",
                "Tópicos Especiais em Tecnologia da Informação I",
                "Empreendedorismo"
            ],
            "TRC-361": [
                "Gerencia de Redes",
                "Projeto Integrador II",
                "Governança de TI",
                "Tópicos Especiais em Tecnologia da Informação II",
            ],
            "TRC-OPT": [
                "Programação Orientada a Objetos",
                "Internet das Coisas - IoT",
                "Estrutura de Dados",
                "Cabeamento Estruturado",
                "Projeto de Sistemas"
            ]
}

